on:
  push:
    paths:
      - "helloworld.cpp"
jobs:
  Run-Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: compile
        run: g++ helloworld.cpp
      - name: List files
        run: ls ${{ github.workspace }}
      - name: Run program
        run: ./a.out
      - name: Set deployment
        run: curl -s -f -d "host=rda-web-prod01.ucar.edu&build_command=/usr/local/decs/bin/metaman_deploy" "https://rda.ucar.edu/cgi-bin/cicd"
