on:
  push:
    paths:
      - "helloworld.cpp"
jobs:
  Run-Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: compile
        run: g++ helloworld.cpp
      - name: List files
        run: ls ${{ github.workspace }}
